alg=input("Digite algo: ")
print("O tipo primitivo de alg é: ",type(alg))
print("Só tem espaço?", alg.isspace())
print("É um número?", alg.isnumeric())
print("É alfabético?", alg.isalpha())
print("É alfanumérico?", alg.isalnum())
print("Está em maiúsculo?", alg.isupper())
print("Está em minúsculo?", alg.islower())
print("Está capitalizado?", alg.istitle())
